package com.kareem.cortex;

import android.app.*;
import android.database.Cursor;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.util.*;

/** Developer harness for calibrating attention decisions against real Cortex data. */
public final class AttentionEvaluationActivity extends Activity {
    VaultDb db;LinearLayout content;int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(getApplicationContext());CognitiveStore.ensure(db);AttentionAdjudicationStore.ensure(db);build();render();}
    @Override protected void onDestroy(){if(db!=null)try{db.close();}catch(Throwable ignored){}db=null;super.onDestroy();}
    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(14),dp(18),dp(28));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);CortexUi.fitSystemBars(this,root);}
    void render(){content.removeAllViews();TextView h=CortexUi.plain(this,"Attention Evaluation",28,CortexUi.TEXT);CortexUi.medium(h);content.addView(h);TextView sub=CortexUi.text(this,"Judge canonical cognitive events, not raw derived rows. Duplicate evidence is consolidated before ranking; stored relevance is not rewritten.",12,CortexUi.MUTED);sub.setPadding(0,dp(5),0,dp(14));content.addView(sub);ArrayList<Row> rows=load(40);Stats s=stats();content.addView(summary(s));if(rows.isEmpty()){TextView e=CortexUi.text(this,"No open attention candidates to evaluate.",13,CortexUi.MUTED);e.setPadding(0,dp(22),0,0);content.addView(e);return;}for(Row r:rows)card(r);}
    View summary(Stats s){LinearLayout box=CortexUi.card(this,20);box.setPadding(dp(14),dp(13),dp(14),dp(13));TextView a=CortexUi.plain(this,s.total+" judged  •  "+s.correct+" correct  •  "+s.tooHigh+" too high  •  "+s.tooLow+" too low",11,CortexUi.TEXT);box.addView(a);if(s.total>0){int acc=Math.round(100f*s.correct/s.total);TextView b=CortexUi.plain(this,"Agreement: "+acc+"%",10,CortexUi.MUTED);b.setPadding(0,dp(5),0,0);box.addView(b);}return box;}
    void card(Row r){LinearLayout c=CortexUi.card(this,18);c.setPadding(dp(14),dp(13),dp(14),dp(13));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);String title=r.item.title.isEmpty()?r.item.attentionKind:r.item.title;TextView t=CortexUi.text(this,clip(title,100),14,CortexUi.TEXT);CortexUi.medium(t);top.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView chip=CortexUi.chip(this,r.learned.band+"  "+r.learned.score,bandColor(r.learned.band),true);top.addView(chip,new LinearLayout.LayoutParams(-2,dp(32)));c.addView(top);
        if(!r.item.body.isEmpty()){TextView body=CortexUi.text(this,clip(r.item.body,220),12,CortexUi.MUTED);body.setPadding(0,dp(6),0,0);body.setMaxLines(4);c.addView(body);}TextView flow=CortexUi.plain(this,"Baseline "+r.baseline.score+" → AI "+(r.ai.available?String.valueOf(r.ai.score):"—")+" → Learned "+r.learned.score+"  •  "+r.item.attentionKind+(r.item.attentionKind.equals(r.item.kind)?"":" (stored "+r.item.kind+")"),10,CortexUi.MUTED);flow.setPadding(0,dp(8),0,0);c.addView(flow);TextView ai=CortexUi.text(this,"AI: "+r.ai.status,10,r.ai.available?CortexUi.SAGE:CortexUi.MUTED);ai.setPadding(0,dp(3),0,0);c.addView(ai);TextView why=CortexUi.text(this,"Why now: "+r.learned.whyNow,11,CortexUi.TEXT);why.setPadding(0,dp(6),0,dp(10));c.addView(why);
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);String[] labels={"CORRECT","TOO HIGH","TOO LOW"};String[] verdicts={"correct","too_high","too_low"};for(int i=0;i<labels.length;i++){final String v=verdicts[i];TextView b=CortexUi.action(this,labels[i],i==0?CortexUi.SAGE:CortexUi.MUTED,false);b.setOnClickListener(x->{judge(r.item.id,v,r.learned.score);Toast.makeText(this,"Recorded "+v.replace('_',' '),Toast.LENGTH_SHORT).show();render();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(42),1);if(i>0)p.setMargins(dp(6),0,0,0);actions.addView(b,p);}c.addView(actions);
        LinearLayout actions2=new LinearLayout(this);actions2.setOrientation(LinearLayout.HORIZONTAL);TextView quiet=CortexUi.action(this,"SHOULD BE QUIET",CortexUi.MUTED,false),now=CortexUi.action(this,"SHOULD BE NOW",CortexUi.ACCENT,false);quiet.setOnClickListener(x->{judge(r.item.id,"should_be_quiet",0);render();});now.setOnClickListener(x->{judge(r.item.id,"should_be_now",100);render();});actions2.addView(quiet,new LinearLayout.LayoutParams(0,dp(42),1));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(0,dp(42),1);np.setMargins(dp(6),dp(6),0,0);actions2.addView(now,np);c.addView(actions2);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(10),0,0);content.addView(c,cp);}
    ArrayList<Row> load(int limit){ArrayList<Row> all=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,kind,title,body,source_key,state,confidence,importance,thread_id,anchor_signal_id,updated_at FROM derived_items WHERE state='open' AND kind IN ('ACTION','WAITING','DECISION') ORDER BY updated_at DESC LIMIT 300",null);long now=System.currentTimeMillis();while(c.moveToNext()){PrimeBriefStore.Item item=new PrimeBriefStore.Item(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getInt(7),c.getLong(8),c.getLong(9),c.getLong(10));AttentionEngine.Decision baseline=AttentionEngine.evaluate(item,now);AiSnapshot ai=ai(item,baseline);AttentionEngine.Decision merged=ai.available?ai.decision:baseline;AttentionEngine.Decision learned=AttentionLearning.apply(db,item,merged);all.add(new Row(item,baseline,learned,ai));}c.close();all.sort((a,b)->{int z=Integer.compare(b.learned.score,a.learned.score);return z!=0?z:Long.compare(b.item.updatedAt,a.item.updatedAt);});ArrayList<Row> out=CandidateConsolidator.consolidate(all,new CandidateConsolidator.ItemAccessor<Row>(){public PrimeBriefStore.Item item(Row r){return r.item;}public int priority(Row r){return r.learned.score;}});out.sort((a,b)->Integer.compare(b.learned.score,a.learned.score));if(out.size()>limit)return new ArrayList<>(out.subList(0,limit));return out;}
    AiSnapshot ai(PrimeBriefStore.Item item,AttentionEngine.Decision baseline){try{Cursor c=db.getReadableDatabase().query("attention_adjudications",new String[]{"item_updated_at","final_score","band","why_now","model_score","confidence","expires_at","provider"},"derived_id=?",new String[]{String.valueOf(item.id)},null,null,"adjudicated_at DESC","1");if(!c.moveToFirst()){c.close();AttentionContextBuilder.Pack p=AttentionContextBuilder.build(this,db,item);return new AiSnapshot(false,baseline.score,baseline,p.usable()?"eligible, no cached adjudication yet":"ineligible: grounded evidence is missing, mixed, or local-only");}long itemUpdated=c.getLong(0),expires=c.getLong(6);double conf=c.getDouble(5);String provider=c.getString(7);if(itemUpdated!=item.updatedAt){c.close();return new AiSnapshot(false,baseline.score,baseline,"stale: candidate changed since adjudication");}if(expires<=System.currentTimeMillis()){c.close();return new AiSnapshot(false,baseline.score,baseline,"expired cache; waiting for background refresh");}if(conf<0.72){c.close();return new AiSnapshot(false,baseline.score,baseline,"AI confidence below 72%; baseline retained");}int score=c.getInt(1),model=c.getInt(4);String why=c.getString(3),bandName=c.getString(2);c.close();AttentionEngine.Band b;try{b=AttentionEngine.Band.valueOf(bandName);}catch(Exception e){b=band(score);}AttentionEngine.Decision d=new AttentionEngine.Decision(score,b,why==null||why.trim().isEmpty()?baseline.whyNow:why,baseline.urgency,baseline.consequence,baseline.responsibility,baseline.temporalPressure,baseline.openLoopPressure,baseline.novelty,conf);return new AiSnapshot(true,model,d,"cached · "+(provider==null?"provider":provider)+" · confidence "+Math.round(conf*100)+"%");}catch(Throwable e){return new AiSnapshot(false,baseline.score,baseline,"diagnostic error: "+e.getClass().getSimpleName());}}
    void judge(long id,String verdict,int target){try{JSONObject v=new JSONObject().put("verdict",verdict).put("target_score",target);CognitiveStore.feedback(db,"derived",id,"attention_eval",v.toString(),"attention_eval_004");}catch(Exception ignored){}}
    Stats stats(){Stats s=new Stats();HashSet<Long> seen=new HashSet<>();Cursor c=db.getReadableDatabase().query("feedback_events",new String[]{"target_id","value_json"},"event_type='attention_eval'",null,null,null,"created_at DESC","500");while(c.moveToNext()){long id=c.getLong(0);if(!seen.add(id))continue;try{String v=new JSONObject(c.getString(1)).optString("verdict","");if(v.isEmpty())continue;s.total++;if("correct".equals(v))s.correct++;else if("too_high".equals(v)||"should_be_quiet".equals(v))s.tooHigh++;else if("too_low".equals(v)||"should_be_now".equals(v))s.tooLow++;}catch(Exception ignored){}}c.close();return s;}
    int bandColor(AttentionEngine.Band b){if(b==AttentionEngine.Band.NOW)return CortexUi.RED;if(b==AttentionEngine.Band.LATER)return CortexUi.ORANGE;if(b==AttentionEngine.Band.WATCHING)return CortexUi.YELLOW;return CortexUi.MUTED;}AttentionEngine.Band band(int s){return s>=72?AttentionEngine.Band.NOW:s>=54?AttentionEngine.Band.LATER:s>=36?AttentionEngine.Band.WATCHING:AttentionEngine.Band.QUIET;}String clip(String s,int n){String x=s==null?"":s.replaceAll("\\s+"," ").trim();return x.length()<=n?x:x.substring(0,n)+"…";}
    static final class Row{final PrimeBriefStore.Item item;final AttentionEngine.Decision baseline,learned;final AiSnapshot ai;Row(PrimeBriefStore.Item i,AttentionEngine.Decision b,AttentionEngine.Decision l,AiSnapshot a){item=i;baseline=b;learned=l;ai=a;}}static final class AiSnapshot{final boolean available;final int score;final AttentionEngine.Decision decision;final String status;AiSnapshot(boolean a,int s,AttentionEngine.Decision d,String st){available=a;score=s;decision=d;status=st;}}static final class Stats{int total,correct,tooHigh,tooLow;}
}
