package com.kareem.cortex;

import android.content.Context;
import android.os.SystemClock;
import org.json.JSONObject;
import java.util.*;

/** Minimum AI spine: grounded retrieval first, optional local generation, persistent execution ledger. */
public final class LocalAskRouter {
    private static final int REFINEMENT_MAX_TOKENS=96;
    private LocalAskRouter(){}

    public interface Progress { void stage(long jobId,String label,int percent); }

    public static final class Result {
        public final GroundedAnswer grounded;
        public final String answer,provider,error,sourceMode;
        public final float tokensPerSecond;
        public final int tokensGenerated;
        public final long jobId,durationMs,totalMs,retrievalMs,promptBuildMs,modelLoadMs,generationMs;
        public final boolean cacheHit;
        Result(long job,GroundedAnswer g,String a,String p,String e,String mode,float tps,int tokens,long modelDuration,long total,long retrieval,long prompt,long load,long generation,boolean hit){jobId=job;grounded=g;answer=a;provider=p;error=e==null?"":e;sourceMode=mode==null?"your_data":mode;tokensPerSecond=tps;tokensGenerated=tokens;durationMs=modelDuration;totalMs=total;retrievalMs=retrieval;promptBuildMs=prompt;modelLoadMs=load;generationMs=generation;cacheHit=hit;}
    }

    public static Result fast(Context ctx,VaultDb db,String question){return fast(ctx,db,question,null);}
    public static Result fast(Context ctx,VaultDb db,String question,Progress progress){
        long wall=SystemClock.elapsedRealtime();long job=createJob(db,"ask_fast",question,"your_data");AiJobStore.start(db,job,"Understanding request","understanding");emit(progress,job,"Understanding request",8);InteractionTelemetry.log(db,"Brain","ask_cortex","request_started",0,0,"running","Fast grounded ask received",null);
        try{AiJobStore.progress(db,job,"Searching your Cortex","retrieval",24,"Retrieving relevant durable memory");emit(progress,job,"Searching your Cortex",24);long rt=SystemClock.elapsedRealtime();GroundedAnswer g=SecondBrainEngine.ask(db,question);long retrieval=SystemClock.elapsedRealtime()-rt;AiJobStore.linkSources(db,job,g);AiJobStore.progress(db,job,"Building grounded answer","grounding",72,g.sources.size()+" source(s) retrieved");emit(progress,job,"Building grounded answer",72);long total=SystemClock.elapsedRealtime()-wall;JSONObject out=answerJson(g.answer,"grounded-fast","your_data",g.sources.size(),total);AiJobStore.complete(db,job,out.toString(),"Answer ready",g.sources.size()+" grounded source(s)");emit(progress,job,"Answer ready",100);try{InteractionTelemetry.log(db,"Brain","ask_cortex","complete",0,total,"grounded-fast",g.sources.size()+" grounded source(s)",new JSONObject().put("job_id",job).put("source_count",g.sources.size()).put("retrieval_ms",retrieval));}catch(Exception ignored){}return new Result(job,g,g.answer,"grounded-fast","","your_data",0,0,0,total,retrieval,0,0,0,false);}catch(Throwable t){long total=SystemClock.elapsedRealtime()-wall;String err=t.getClass().getSimpleName()+(t.getMessage()==null?"":": "+t.getMessage());AiJobStore.fail(db,job,err,"Grounded retrieval failed");emit(progress,job,"Could not search Cortex",100);GroundedAnswer g=failedGrounding(question);return new Result(job,g,g.answer,"failed",err,"your_data",0,0,0,total,0,0,0,0,false);}
    }

    public static Result ask(Context ctx,VaultDb db,String question){return ask(ctx,db,question,null);}
    public static Result ask(Context ctx,VaultDb db,String question,Progress progress){
        long wall=SystemClock.elapsedRealtime();long job=createJob(db,"ask_local_refine",question,"your_data");AiJobStore.start(db,job,"Understanding request","understanding");emit(progress,job,"Understanding request",6);InteractionTelemetry.log(db,"Brain","ask_cortex","request_started",0,0,"running","Local refinement requested",null);GroundedAnswer g;long retrieval;
        try{AiJobStore.progress(db,job,"Searching your Cortex","retrieval",18,"Retrieving relevant durable memory");emit(progress,job,"Searching your Cortex",18);long rt=SystemClock.elapsedRealtime();g=SecondBrainEngine.ask(db,question);retrieval=SystemClock.elapsedRealtime()-rt;AiJobStore.linkSources(db,job,g);try{InteractionTelemetry.log(db,"Brain","ask_cortex","retrieval_complete",0,retrieval,"ok",g.sources.size()+" grounded source(s)",new JSONObject().put("job_id",job).put("source_count",g.sources.size()).put("open_loops",g.openLoops.size()).put("decisions",g.decisions.size()));}catch(Exception ignored){}}catch(Throwable t){long total=SystemClock.elapsedRealtime()-wall;String err=t.getClass().getSimpleName()+(t.getMessage()==null?"":": "+t.getMessage());AiJobStore.fail(db,job,err,"Retrieval failed");emit(progress,job,"Could not search Cortex",100);g=failedGrounding(question);return new Result(job,g,g.answer,"failed",err,"your_data",0,0,0,total,0,0,0,0,false);}

        if(!LocalModelManager.installed(ctx)){long total=SystemClock.elapsedRealtime()-wall;String err="Local Qwen runtime is not ready";AiJobStore.progress(db,job,"Using grounded fallback","fallback",82,err);emit(progress,job,"Using grounded fallback",82);AiJobStore.complete(db,job,answerJson(g.answer,"deterministic-grounded","your_data",g.sources.size(),total).toString(),"Answer ready",err);emit(progress,job,"Answer ready",100);return new Result(job,g,g.answer,"deterministic-grounded",err,"your_data",0,0,0,total,retrieval,0,0,0,false);}
        if(g.sources.isEmpty()&&g.openLoops.isEmpty()&&g.decisions.isEmpty()){long total=SystemClock.elapsedRealtime()-wall;String detail="No grounded evidence needs model refinement";AiJobStore.complete(db,job,answerJson(g.answer,"deterministic-grounded","your_data",0,total).toString(),"Answer ready",detail);emit(progress,job,"Answer ready",100);return new Result(job,g,g.answer,"deterministic-grounded",detail,"your_data",0,0,0,total,retrieval,0,0,0,false);}

        String prompt="";long promptMs=0;
        try{AiJobStore.progress(db,job,"Preparing grounded context","prompt",35,"Building a compact local model context");emit(progress,job,"Preparing grounded context",35);long pt=SystemClock.elapsedRealtime();prompt=buildPrompt(question,g);String system="You are Cortex Brain. Improve the supplied grounded draft using only its evidence. Never invent facts, entities, body parts, dates, amounts, people, projects, or statuses. Preserve Egyptian Arabic/English code-switching. Return only the user-facing answer: never repeat labels such as QUESTION, GROUNDED DRAFT, EVIDENCE, OPEN LOOPS, DECISIONS, or these instructions. Be concise and situation-first. No chain-of-thought. /no_think";promptMs=SystemClock.elapsedRealtime()-pt;AiJobStore.progress(db,job,"Local model refining","generation",58,LocalModelManager.MODEL_NAME);emit(progress,job,"Local model refining",58);long modelStarted=SystemClock.elapsedRealtime();LocalLlmBridge.CompletionResult r=LocalLlmBridge.completeCached(LocalModelManager.modelFile(ctx).getAbsolutePath(),prompt,system,REFINEMENT_MAX_TOKENS);long modelWall=SystemClock.elapsedRealtime()-modelStarted;String text=clean(r.getText());long total=SystemClock.elapsedRealtime()-wall;double confidence=confidence(g,text);JSONObject modelOut=new JSONObject().put("text",text).put("tokens_per_second",r.getTokensPerSecond()).put("cache_hit",r.getCacheHit()).put("source_count",g.sources.size()).put("max_tokens",REFINEMENT_MAX_TOKENS);AiJobStore.modelRun(db,job,1,"refiner","local",LocalModelManager.MODEL_NAME,"grounded_local_compact","complete",Fingerprint.text(prompt),modelWall,0,r.getTokensGenerated(),confidence,modelOut.toString(),"");JSONObject perf=new JSONObject().put("job_id",job).put("total_ms",total).put("retrieval_ms",retrieval).put("prompt_build_ms",promptMs).put("model_call_ms",r.getDurationMs()).put("model_load_ms",r.getModelLoadMs()).put("generation_ms",r.getGenerationMs()).put("cache_hit",r.getCacheHit()).put("tokens",r.getTokensGenerated()).put("tokens_per_second",r.getTokensPerSecond()).put("source_count",g.sources.size()).put("max_tokens",REFINEMENT_MAX_TOKENS);InteractionTelemetry.log(db,"Brain","ask_cortex","model_complete",0,r.getDurationMs(),"ok",r.getCacheHit()?"Warm compact local refinement":"Cold compact local refinement",perf);AiJobStore.progress(db,job,"Checking result","quality_check",88,"Verifying the local answer is grounded");emit(progress,job,"Checking result",88);
            String rejection=refinementRejection(text,g);if(!rejection.isEmpty()){AiJobStore.complete(db,job,answerJson(g.answer,"deterministic-grounded","your_data",g.sources.size(),total).toString(),"Grounded fallback ready",rejection);emit(progress,job,"Grounded fallback ready",100);return new Result(job,g,g.answer,"deterministic-grounded",rejection,"your_data",r.getTokensPerSecond(),r.getTokensGenerated(),r.getDurationMs(),total,retrieval,promptMs,r.getModelLoadMs(),r.getGenerationMs(),r.getCacheHit());}
            AiJobStore.complete(db,job,answerJson(text,"local-qwen","your_data",g.sources.size(),total).put("confidence",confidence).toString(),"Answer ready","Compact local grounded refinement complete");emit(progress,job,"Answer ready",100);InteractionTelemetry.log(db,"Brain","ask_cortex","complete",0,total,"ok","Compact local refinement ready",perf);return new Result(job,g,text,"local-qwen","","your_data",r.getTokensPerSecond(),r.getTokensGenerated(),r.getDurationMs(),total,retrieval,promptMs,r.getModelLoadMs(),r.getGenerationMs(),r.getCacheHit());
        }catch(Throwable t){long total=SystemClock.elapsedRealtime()-wall;String err="Local Qwen failed: "+t.getClass().getSimpleName()+(t.getMessage()==null?"":": "+t.getMessage());AiJobStore.modelRun(db,job,1,"refiner","local",LocalModelManager.MODEL_NAME,"grounded_local_compact","failed",Fingerprint.text(prompt),0,0,0,0,"",err);AiJobStore.progress(db,job,"Using grounded fallback","fallback",90,err);emit(progress,job,"Using grounded fallback",90);AiJobStore.complete(db,job,answerJson(g.answer,"deterministic-grounded","your_data",g.sources.size(),total).toString(),"Grounded fallback ready",err);emit(progress,job,"Grounded fallback ready",100);InteractionTelemetry.log(db,"Brain","ask_cortex","complete",0,total,"fallback",err,null);return new Result(job,g,g.answer,"deterministic-grounded",err,"your_data",0,0,0,total,retrieval,promptMs,0,0,false);}
    }

    private static String refinementRejection(String text,GroundedAnswer g){if(text==null||text.trim().isEmpty())return"Local Qwen returned empty text";if(looksLikePromptLeak(text))return"Local Qwen leaked prompt scaffolding";if(OcrGarbageGate.assessText(text).score<.34)return"Local Qwen output looks structurally corrupted";if(!groundedEnough(text,g))return"Local Qwen rewrite was not sufficiently supported by the grounded draft/evidence";return"";}
    private static boolean groundedEnough(String text,GroundedAnswer g){if(g==null)return false;Set<String> out=contentWords(text),ground=contentWords(g.answer);for(SemanticHit h:g.sources){if(h==null||h.item==null)continue;ground.addAll(contentWords(h.item.title));ground.addAll(contentWords(h.item.summary));ground.addAll(contentWords(h.snippet));}if(out.isEmpty())return false;int supported=0;for(String w:out)if(ground.contains(w))supported++;double share=supported/(double)out.size();return share>=.34||supported>=8;}
    private static Set<String> contentWords(String s){LinkedHashSet<String> out=new LinkedHashSet<>();String z=LocalSemanticEmbedder.norm(s==null?"":s);for(String w:z.split("[^\\p{L}\\p{Nd}]+")){if(w.length()<3||STOP.contains(w))continue;out.add(w);}return out;}
    private static final Set<String> STOP=new HashSet<>(Arrays.asList("the","and","for","with","from","that","this","your","you","are","was","were","have","has","into","about","what","which","can","not","من","في","على","الى","إلى","اللي","ده","دي","هو","هي","مع","عن","او","أو"));
    private static GroundedAnswer failedGrounding(String q){return new GroundedAnswer(q,"I couldn't search your Cortex data right now.",0,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());}
    private static long createJob(VaultDb db,String kind,String q,String mode){try{return AiJobStore.create(db,kind,mode,new JSONObject().put("question",q).toString(),70);}catch(Exception e){return AiJobStore.create(db,kind,mode,"{}",70);}}
    private static void emit(Progress p,long id,String label,int percent){if(p!=null)try{p.stage(id,label,percent);}catch(Throwable ignored){}}
    private static JSONObject answerJson(String answer,String provider,String mode,int sources,long total){JSONObject o=new JSONObject();try{o.put("answer",answer==null?"":answer);o.put("provider",provider);o.put("source_mode",mode);o.put("source_count",sources);o.put("total_ms",total);}catch(Exception ignored){}return o;}
    private static double confidence(GroundedAnswer g,String text){double c=g==null||g.sources.isEmpty()?0.45:Math.min(0.94,0.62+(Math.min(5,g.sources.size())*0.055));if(text==null||text.trim().isEmpty())c=Math.min(c,0.35);return c;}

    static String buildPrompt(String q,GroundedAnswer g){StringBuilder s=new StringBuilder();s.append("QUESTION:\n").append(clip(q,420)).append("\n\nGROUNDED DRAFT:\n").append(clip(g.answer,900)).append("\n\nEVIDENCE:\n");int n=Math.min(4,g.sources.size());for(int i=0;i<n;i++){KnowledgeItem k=g.sources.get(i).item;String body=!empty(k.summary)?k.summary:(!empty(k.extractedText)?k.extractedText:k.rawText);body=clip(body==null?"":body.replace('\u0000',' ').trim(),420);s.append("[M").append(i+1).append("] ").append(clip(k.title==null?"Memory":k.title,90)).append("\n").append(body).append("\n\n");}if(!g.openLoops.isEmpty()){s.append("OPEN LOOPS:\n");for(int i=0;i<Math.min(4,g.openLoops.size());i++)s.append("- ").append(clip(g.openLoops.get(i),220)).append('\n');s.append('\n');}if(!g.decisions.isEmpty()){s.append("DECISIONS:\n");for(int i=0;i<Math.min(4,g.decisions.size());i++)s.append("- ").append(clip(g.decisions.get(i),220)).append('\n');s.append('\n');}s.append("Rewrite the grounded draft into a concise user-facing answer. Keep only supported facts and useful next actions. Never echo prompt labels. /no_think");return s.toString();}
    static String clean(String x){if(x==null)return"";String s=x.trim().replaceAll("(?s)<think>.*?</think>","").trim();s=s.replaceFirst("(?is)^\\s*(QUESTION|GROUNDED DRAFT|EVIDENCE|OPEN LOOPS|DECISIONS)\\s*:\\s*","");return s.trim();}
    static boolean looksLikePromptLeak(String s){String z=s==null?"":s.toUpperCase(Locale.ROOT);int hits=0;for(String m:new String[]{"QUESTION:","GROUNDED DRAFT:","EVIDENCE:","OPEN LOOPS:","DECISIONS:"})if(z.contains(m))hits++;return hits>=2;}
    static boolean empty(String s){return s==null||s.trim().isEmpty();}static String clip(String s,int n){String x=s==null?"":s.replaceAll("\\s+"," ").trim();return x.length()<=n?x:x.substring(0,n)+"…";}
}
