package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.*;
import java.io.*;
import java.net.*;

public class LocalModelDownloadService extends Service {
    public static final String ACTION_START="com.kareem.cortex.MODEL_START",ACTION_RESUME="com.kareem.cortex.MODEL_RESUME",ACTION_PAUSE="com.kareem.cortex.MODEL_PAUSE",ACTION_CANCEL="com.kareem.cortex.MODEL_CANCEL";
    private static final String CHANNEL="cortex_model_download";private static final int NOTIFY_ID=42042;private volatile boolean paused=false,canceled=false,running=false;private PowerManager.WakeLock wake;

    @Override public void onCreate(){super.onCreate();NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(CHANNEL,"Cortex local brain download",NotificationManager.IMPORTANCE_LOW));}
    @Override public int onStartCommand(Intent intent,int flags,int startId){String a=intent==null?ACTION_RESUME:intent.getAction();if(ACTION_PAUSE.equals(a)){paused=true;LocalModelManager.Status s=LocalModelManager.status(this);LocalModelManager.setState(this,"paused",s.done,s.total,0,"Paused by user",s.httpStatus,s.currentUrl,s.rangeSupported,s.retryCount);updateNotification("Paused",s.percent,s.done,s.total,false);stopForeground(false);stopSelf();return START_NOT_STICKY;}if(ACTION_CANCEL.equals(a)){canceled=true;paused=false;File p=LocalModelManager.partFile(this);if(p.exists())p.delete();File f=LocalModelManager.modelFile(this);if(f.exists()&&!LocalModelManager.verified(this))f.delete();LocalModelManager.clearVerified(this);LocalModelManager.setState(this,"canceled",0,0,0,"Canceled by user",0,LocalModelManager.MODEL_URL,false,0);updateNotification("Canceled",0,0,0,false);stopForeground(false);stopSelf();return START_NOT_STICKY;}if(!running){paused=false;canceled=false;startForeground(NOTIFY_ID,notification("Connecting",0,0,0,true));new Thread(this::runDownload,"cortex-model-download").start();}return START_STICKY;}
    @Override public IBinder onBind(Intent i){return null;}

    private void runDownload(){running=true;acquireWake();int retry=0;try{while(!paused&&!canceled){try{transferOnce(retry);return;}catch(Exception e){if(paused||canceled)return;retry++;LocalModelManager.Status s=LocalModelManager.status(this);if(retry>8){LocalModelManager.setState(this,"failed",s.done,s.total,0,e.getClass().getSimpleName()+": "+safe(e.getMessage()),s.httpStatus,s.currentUrl,s.rangeSupported,retry);updateNotification("Download failed • tap Resume",s.percent,s.done,s.total,false);return;}long wait=Math.min(30000L,2000L*(1L<<Math.min(4,retry-1)));LocalModelManager.setState(this,"retrying",LocalModelManager.partialSize(this),s.total,0,e.getClass().getSimpleName()+": "+safe(e.getMessage()),s.httpStatus,s.currentUrl,s.rangeSupported,retry);updateNotification("Retrying in "+(wait/1000)+"s",s.percent,LocalModelManager.partialSize(this),s.total,true);sleepInterruptibly(wait);}}}finally{running=false;releaseWake();String state=LocalModelManager.transferState(this);if(!LocalModelManager.verified(this)&&!"failed".equals(state)&&!"verification_failed".equals(state)&&!"paused".equals(state)&&!"canceled".equals(state)){LocalModelManager.Status s=LocalModelManager.status(this);LocalModelManager.setState(this,"paused",s.done,s.total,0,"Transfer stopped",s.httpStatus,s.currentUrl,s.rangeSupported,s.retryCount);}stopForeground(false);stopSelf();}}

    private void transferOnce(int retry)throws Exception{File part=LocalModelManager.partFile(this),finalFile=LocalModelManager.modelFile(this);File parent=part.getParentFile();if(parent!=null&&!parent.exists())parent.mkdirs();long offset=part.exists()?part.length():0;ConnectionResult cr=open(LocalModelManager.MODEL_URL,offset);HttpURLConnection c=cr.conn;int code=cr.code;boolean append=offset>0&&code==206;if(offset>0&&code==200){if(part.exists())part.delete();offset=0;append=false;}if(code!=200&&code!=206)throw new IOException("HTTP "+code);long total=totalBytes(c,offset,code);boolean ranges=code==206||"bytes".equalsIgnoreCase(c.getHeaderField("Accept-Ranges"));LocalModelManager.setState(this,"downloading",offset,total,0,"",code,cr.url,ranges,retry);long lastAt=System.currentTimeMillis(),lastBytes=offset,done=offset;byte[] buf=new byte[256*1024];try(InputStream in=new BufferedInputStream(c.getInputStream(),512*1024);OutputStream out=new BufferedOutputStream(new FileOutputStream(part,append),512*1024)){int n;while((n=in.read(buf))!=-1){if(paused||canceled)break;out.write(buf,0,n);done+=n;long now=System.currentTimeMillis();if(now-lastAt>=800||done-lastBytes>=4L*1024*1024){out.flush();long speed=(done-lastBytes)*1000L/Math.max(1,now-lastAt);LocalModelManager.setState(this,"downloading",done,total,speed,"",code,cr.url,ranges,retry);int pct=total>0?(int)Math.min(100,done*100/total):0;updateNotification("Downloading "+LocalModelManager.MODEL_NAME,pct,done,total,true);lastAt=now;lastBytes=done;}}out.flush();}finally{c.disconnect();}if(paused||canceled)return;if(total>0&&part.length()!=total)throw new EOFException("Connection ended at "+part.length()+" of "+total+" bytes");if(part.length()<1_200_000_000L)throw new EOFException("Downloaded file is too small");if(finalFile.exists()&&!finalFile.delete())throw new IOException("Cannot replace model file");if(!part.renameTo(finalFile)){copy(part,finalFile);if(!part.delete())part.deleteOnExit();}LocalModelManager.setState(this,"verifying",finalFile.length(),finalFile.length(),0,"",code,cr.url,ranges,retry);updateNotification("Verifying SHA-256 + GGUF",100,finalFile.length(),finalFile.length(),true);LocalModelManager.Verification v=LocalModelManager.verify(this);if(!v.ok){updateNotification(v.message,100,finalFile.length(),finalFile.length(),false);return;}updateNotification("Verified model asset",100,finalFile.length(),finalFile.length(),false);}

    private ConnectionResult open(String start,long offset)throws Exception{String u=start;for(int i=0;i<10;i++){HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(20000);c.setReadTimeout(45000);c.setRequestProperty("User-Agent","Cortex/1.0 Android");c.setRequestProperty("Accept-Encoding","identity");if(offset>0)c.setRequestProperty("Range","bytes="+offset+"-");int code=c.getResponseCode();if(code==301||code==302||code==303||code==307||code==308){String loc=c.getHeaderField("Location");c.disconnect();if(loc==null||loc.isEmpty())throw new IOException("Redirect without Location");u=new URL(new URL(u),loc).toString();continue;}return new ConnectionResult(c,code,u);}throw new IOException("Too many redirects");}
    private long totalBytes(HttpURLConnection c,long offset,int code){String cr=c.getHeaderField("Content-Range");if(cr!=null){int slash=cr.lastIndexOf('/');if(slash>=0)try{return Long.parseLong(cr.substring(slash+1).trim());}catch(Exception ignored){}}long len=c.getContentLengthLong();return len>0?(code==206?offset+len:len):0;}
    private void sleepInterruptibly(long ms){long end=System.currentTimeMillis()+ms;while(!paused&&!canceled&&System.currentTimeMillis()<end)try{Thread.sleep(Math.min(500,Math.max(1,end-System.currentTimeMillis())));}catch(InterruptedException ignored){break;}}
    private void copy(File a,File b)throws Exception{try(InputStream in=new BufferedInputStream(new FileInputStream(a));OutputStream out=new BufferedOutputStream(new FileOutputStream(b))){byte[] x=new byte[1024*1024];int n;while((n=in.read(x))!=-1)out.write(x,0,n);}}

    private Notification notification(String title,int pct,long done,long total,boolean ongoing){Intent open=new Intent(this,EnvironmentActivity.class);PendingIntent content=PendingIntent.getActivity(this,11,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);PendingIntent pause=PendingIntent.getService(this,12,new Intent(this,LocalModelDownloadService.class).setAction(ACTION_PAUSE),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);PendingIntent cancel=PendingIntent.getService(this,13,new Intent(this,LocalModelDownloadService.class).setAction(ACTION_CANCEL),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setSmallIcon(android.R.drawable.stat_sys_download).setContentTitle(title).setContentIntent(content).setOngoing(ongoing).setOnlyAlertOnce(true).setCategory(Notification.CATEGORY_PROGRESS);String sub=done>0?LocalModelManager.human(done)+(total>0?" / "+LocalModelManager.human(total):""):"Cortex-owned resumable download";b.setContentText(sub);if(total>0)b.setProgress(100,Math.max(0,Math.min(100,pct)),false);else if(ongoing)b.setProgress(0,0,true);if(ongoing){b.addAction(new Notification.Action.Builder(android.R.drawable.ic_media_pause,"Pause",pause).build());b.addAction(new Notification.Action.Builder(android.R.drawable.ic_menu_close_clear_cancel,"Cancel",cancel).build());}return b.build();}
    private void updateNotification(String title,int pct,long done,long total,boolean ongoing){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(NOTIFY_ID,notification(title,pct,done,total,ongoing));}
    private void acquireWake(){try{PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);wake=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"Cortex:modelDownload");wake.acquire(6L*60*60*1000);}catch(Exception ignored){}}
    private void releaseWake(){try{if(wake!=null&&wake.isHeld())wake.release();}catch(Exception ignored){}}
    private String safe(String s){return s==null?"":s.length()>140?s.substring(0,140):s;}
    private static class ConnectionResult{final HttpURLConnection conn;final int code;final String url;ConnectionResult(HttpURLConnection c,int x,String u){conn=c;code=x;url=u;}}
}
