package com.kareem.cortex;

import android.database.Cursor;
import java.util.*;
import java.util.regex.*;

public final class SecondBrainEngine {
    private SecondBrainEngine(){}

    public static GroundedAnswer ask(VaultDb db,String question){
        String q=question==null?"":question.trim();
        // Truth-critical intent/lifecycle routing must win before broad operational aggregation.
        GroundedAnswer intent=CognitiveIntentRouter.tryAnswer(db,q);if(intent!=null)return intent;
        GroundedAnswer situation=SituationTruthResolver.tryAnswer(db,q);if(situation!=null)return situation;
        GroundedAnswer operational=AskOperationalEngine.tryAnswer(db,q);if(operational!=null)return operational;
        ArrayList<SemanticHit> hits=SemanticIndex.searchForAsk(db,q,8);ArrayList<String> loops=new ArrayList<>(),decisions=new ArrayList<>();boolean wantsLoops=hasAny(q,"todo","task","open loop","follow up","pending","need to","لازم","محتاج","متابعة","معلق","ناقص","اعمل ايه","أعمل ايه");boolean wantsDecisions=hasAny(q,"decision","decided","agreed","approved","choice","قرار","قررنا","اتفقنا","اختيار","اعتمدنا");if(wantsLoops)for(BrainOpenLoop l:openLoops(db,80))if(relevant(q,l.action+" "+l.title)||sourceContains(hits,l.itemId))loops.add(l.action+(empty(l.due)?"":" — "+l.due)+" [M"+sourceNumber(hits,l.itemId)+"]");if(wantsDecisions)decisions.addAll(decisions(db,hits,12));if(hits.isEmpty()||hits.get(0).score<0.105)return new GroundedAnswer(q,"I don't have enough evidence in Cortex to answer that reliably.",0,hits,loops,decisions);
        if(wantsLoops&&!loops.isEmpty())return new GroundedAnswer(q,bulletAnswer("The open items I found are",loops),confidence(hits),hits,loops,decisions);if(wantsDecisions&&!decisions.isEmpty())return new GroundedAnswer(q,bulletAnswer("The decisions I can support from your memory are",decisions),confidence(hits),hits,loops,decisions);
        ArrayList<Candidate> candidates=new ArrayList<>();Set<String> qwords=words(q);for(int i=0;i<hits.size();i++){SemanticHit h=hits.get(i);String body=bestBody(h);int source=i+1;for(String s:sentences(body)){String clean=s.replaceAll("\\s+"," ").trim();if(clean.length()<18)continue;if(clean.length()>420)clean=clean.substring(0,420)+"…";Set<String> sw=words(clean);int overlap=0;for(String w:qwords)if(sw.contains(w))overlap++;double score=h.score+(overlap*0.08)+(i==0?0.08:0);candidates.add(new Candidate(clean,score,source));}}
        candidates.sort((a,b)->Double.compare(b.score,a.score));ArrayList<Candidate> chosen=new ArrayList<>();Set<String> seen=new HashSet<>();for(Candidate c:candidates){String key=LocalSemanticEmbedder.norm(c.text);if(key.length()>90)key=key.substring(0,90);if(seen.add(key)){chosen.add(c);if(chosen.size()>=3)break;}}if(chosen.isEmpty()){SemanticHit h=hits.get(0);String x=!empty(h.item.summary)?h.item.summary:h.snippet;return new GroundedAnswer(q,x+" [M1]",confidence(hits),hits,loops,decisions);}StringBuilder ans=new StringBuilder();if(chosen.size()==1)ans.append(chosen.get(0).text).append(" [M").append(chosen.get(0).source).append(']');else{ans.append("Based on your saved memory:\n");for(Candidate c:chosen)ans.append("• ").append(c.text).append(" [M").append(c.source).append("]\n");}return new GroundedAnswer(q,ans.toString().trim(),confidence(hits),hits,loops,decisions);
    }

    /** Screenshot OCR is evidence, not a task, and imported contacts are never implicit tasks. */
    public static ArrayList<BrainOpenLoop> openLoops(VaultDb db,int limit){ArrayList<BrainOpenLoop> out=new ArrayList<>();String sql="SELECT a.id,a.item_id,a.action_text,a.due_text,k.title,k.category,a.created_at FROM actions a JOIN knowledge_items k ON k.id=a.item_id LEFT JOIN smart_inbox si ON si.item_id=k.id WHERE a.status='open' AND NOT (k.type='CONTACT' AND k.source='contacts_sync') AND (k.type NOT IN ('SCREENSHOT','IMAGE') OR COALESCE(si.manual_bucket,0)=1) ORDER BY CASE WHEN a.due_text IS NULL OR a.due_text='' THEN 1 ELSE 0 END,a.created_at DESC LIMIT ?";Cursor c=db.getReadableDatabase().rawQuery(sql,new String[]{String.valueOf(limit*3)});while(c.moveToNext()){KnowledgeItem k=db.getById(c.getLong(1));if(!SituationTruthResolver.allowAskMemory(db,k))continue;out.add(new BrainOpenLoop(c.getLong(0),c.getLong(1),nz(c.getString(2)),nz(c.getString(3)),nz(c.getString(4)),nz(c.getString(5)),c.getLong(6)));if(out.size()>=limit)break;}c.close();return out;}

    public static ArrayList<String> decisions(VaultDb db,ArrayList<SemanticHit> sources,int limit){ArrayList<String> out=new ArrayList<>();Set<String> seen=new LinkedHashSet<>();for(int i=0;i<sources.size();i++){SemanticHit h=sources.get(i);String body=allText(h.item);for(String s:sentences(body)){String low=LocalSemanticEmbedder.norm(s);if(hasAny(low,"decided","agreed","approved","selected","chosen","final","قررنا","اتفقنا","تم اعتماد","اعتمدنا","المعتمد","اختيارنا","القرار")){String x=s.trim();if(x.length()>280)x=x.substring(0,280)+"…";String key=LocalSemanticEmbedder.norm(x);if(seen.add(key)){out.add(x+" [M"+(i+1)+"]");if(out.size()>=limit)return out;}}}}return out;}
    public static ArrayList<BrainNode> graph(VaultDb db,int limit){HashMap<String,MutableNode> nodes=new HashMap<>();ArrayList<KnowledgeItem> items=db.lexicalSearch("",500);Pattern personEn=Pattern.compile("(?i)\\b(?:dr|eng|mr|mrs|ms|prof)\\.?\\s+([A-Z][A-Za-z'-]+(?:\\s+[A-Z][A-Za-z'-]+){0,3})");Pattern personAr=Pattern.compile("(?:دكتور|د\\.|م\\.|مهندس|أستاذ|استاذ)\\s+([\\p{IsArabic}]{2,}(?:\\s+[\\p{IsArabic}]{2,}){0,3})");Pattern projectEn=Pattern.compile("(?i)\\b(?:project|job|site)\\s*[:#-]?\\s*([A-Za-z0-9][A-Za-z0-9 _-]{2,45})");Pattern projectAr=Pattern.compile("(?:مشروع|موقع)\\s*[:#-]?\\s*([\\p{IsArabic}A-Za-z0-9][\\p{IsArabic}A-Za-z0-9 _-]{2,45})");for(KnowledgeItem k:items){String t=allText(k);scan(nodes,personEn,t,"PERSON",k);scan(nodes,personAr,t,"PERSON",k);scan(nodes,projectEn,t,"PROJECT",k);scan(nodes,projectAr,t,"PROJECT",k);for(String tag:nz(k.tags).split(",")){String x=tag.trim();if(x.length()>2&&x.length()<48)addNode(nodes,"TOPIC",x,k);}}ArrayList<BrainNode> out=new ArrayList<>();for(MutableNode n:nodes.values())if(n.count>=2||!"TOPIC".equals(n.type))out.add(new BrainNode(n.type,n.label,n.count,n.itemId,n.latest));out.sort((a,b)->{int x=Integer.compare(b.mentions,a.mentions);return x!=0?x:Long.compare(b.latestAt,a.latestAt);});if(out.size()>limit)return new ArrayList<>(out.subList(0,limit));return out;}
    public static ArrayList<KnowledgeItem> context(VaultDb db,BrainNode node,int limit){ArrayList<SemanticHit> hits=SemanticIndex.search(db,node.label,limit);ArrayList<KnowledgeItem> out=new ArrayList<>();for(SemanticHit h:hits)out.add(h.item);return out;}
    private static void scan(HashMap<String,MutableNode> nodes,Pattern p,String text,String type,KnowledgeItem k){Matcher m=p.matcher(text);while(m.find()){String label=m.group(1).trim().replaceAll("\\s+"," ");if(label.length()>1)addNode(nodes,type,label,k);}}
    private static void addNode(HashMap<String,MutableNode> nodes,String type,String label,KnowledgeItem k){String clean=label.replaceAll("[.,;:!?؟]+$","").trim();if(clean.isEmpty())return;String key=type+"|"+LocalSemanticEmbedder.norm(clean);MutableNode n=nodes.get(key);if(n==null){n=new MutableNode();n.type=type;n.label=clean;nodes.put(key,n);}n.count++;if(k.createdAt>=n.latest){n.latest=k.createdAt;n.itemId=k.id;}}
    private static String bestBody(SemanticHit h){if(!empty(h.snippet)&&h.snippet.length()>35)return h.snippet;if(!empty(h.item.summary))return h.item.summary;return allText(h.item);}private static String allText(KnowledgeItem k){return nz(k.title)+". "+nz(k.summary)+". "+nz(k.extractedText)+". "+nz(k.rawText);}private static List<String> sentences(String s){return Arrays.asList(nz(s).replace('\n',' ').split("(?<=[.!?؟])\\s+|\\s+[•▪◦]\\s+"));}private static Set<String> words(String s){LinkedHashSet<String> out=new LinkedHashSet<>();for(String w:LocalSemanticEmbedder.norm(s).split("[^\\p{L}\\p{Nd}]+"))if(w.length()>2)out.add(w);return out;}private static boolean relevant(String q,String text){Set<String> a=words(q),b=words(text);for(String w:a)if(b.contains(w))return true;return a.isEmpty();}private static boolean sourceContains(ArrayList<SemanticHit> hits,long id){for(SemanticHit h:hits)if(h.item.id==id)return true;return false;}private static int sourceNumber(ArrayList<SemanticHit> hits,long id){for(int i=0;i<hits.size();i++)if(hits.get(i).item.id==id)return i+1;return 1;}private static double confidence(ArrayList<SemanticHit> h){if(h.isEmpty())return 0;double top=Math.min(1,h.get(0).score);double second=h.size()>1?Math.min(1,h.get(1).score):top*.7;return Math.min(.98,Math.max(.2,top*.7+second*.3));}private static String bulletAnswer(String intro,ArrayList<String> xs){StringBuilder s=new StringBuilder(intro).append(":\n");for(int i=0;i<Math.min(8,xs.size());i++)s.append("• ").append(xs.get(i)).append('\n');return s.toString().trim();}private static boolean hasAny(String text,String... keys){String n=LocalSemanticEmbedder.norm(text);for(String k:keys)if(n.contains(LocalSemanticEmbedder.norm(k)))return true;return false;}private static boolean empty(String s){return s==null||s.trim().isEmpty();}private static String nz(String s){return s==null?"":s;}private static class Candidate{String text;double score;int source;Candidate(String t,double s,int i){text=t;score=s;source=i;}}private static class MutableNode{String type,label;int count;long itemId,latest;}
}
