package com.kareem.cortex;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import java.util.*;

public class VaultDb extends SQLiteOpenHelper {
    private static final String DB="cortex.db";
    public VaultDb(Context c){ super(c,DB,null,CognitiveSchema.DB_VERSION); }

    @Override public void onCreate(SQLiteDatabase db){ createV4(db);CognitiveSchema.ensure(db); }
    private void createV4(SQLiteDatabase db){
        db.execSQL("CREATE TABLE knowledge_items(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,source TEXT,title TEXT NOT NULL,raw_text TEXT,extracted_text TEXT,summary TEXT,category TEXT,tags TEXT,attachment_path TEXT,status TEXT DEFAULT 'queued',fingerprint TEXT,analysis_error TEXT,metadata_json TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");
        db.execSQL("CREATE INDEX idx_ki_created ON knowledge_items(created_at DESC)");db.execSQL("CREATE INDEX idx_ki_category ON knowledge_items(category)");db.execSQL("CREATE INDEX idx_ki_status ON knowledge_items(status)");db.execSQL("CREATE INDEX idx_ki_fingerprint ON knowledge_items(fingerprint)");
        db.execSQL("CREATE TABLE analyses(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,engine TEXT,version TEXT,output_json TEXT,created_at INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE entities(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,kind TEXT,value TEXT,confidence REAL,created_at INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE actions(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,action_text TEXT,due_text TEXT,status TEXT DEFAULT 'open',created_at INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE relations(id INTEGER PRIMARY KEY AUTOINCREMENT,from_item_id INTEGER NOT NULL,to_item_id INTEGER NOT NULL,relation TEXT,confidence REAL,created_at INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE examples(id INTEGER PRIMARY KEY AUTOINCREMENT,prompt_item_id INTEGER NOT NULL,input_item_id INTEGER,output_item_id INTEGER NOT NULL,rating INTEGER DEFAULT 0,notes TEXT,created_at INTEGER NOT NULL)");
        createSemanticTables(db);createVisionTables(db);
    }
    private void createSemanticTables(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS memory_chunks(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,chunk_index INTEGER NOT NULL,chunk_text TEXT NOT NULL,created_at INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_chunks_item ON memory_chunks(item_id)");db.execSQL("CREATE TABLE IF NOT EXISTS embeddings(id INTEGER PRIMARY KEY AUTOINCREMENT,chunk_id INTEGER NOT NULL UNIQUE,provider TEXT NOT NULL,version TEXT NOT NULL,dims INTEGER NOT NULL,vector BLOB NOT NULL,updated_at INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_embed_provider ON embeddings(provider,version)");}
    private void createVisionTables(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS vision_fields(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,field_key TEXT NOT NULL,field_value TEXT NOT NULL,confidence REAL DEFAULT 0,created_at INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_vision_item ON vision_fields(item_id)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_vision_key ON vision_fields(field_key)");}

    @Override public void onUpgrade(SQLiteDatabase db,int oldV,int newV){
        if(oldV<2){db.beginTransaction();try{
            db.execSQL("ALTER TABLE knowledge_items ADD COLUMN extracted_text TEXT");db.execSQL("ALTER TABLE knowledge_items ADD COLUMN fingerprint TEXT");db.execSQL("ALTER TABLE knowledge_items ADD COLUMN analysis_error TEXT");db.execSQL("ALTER TABLE knowledge_items ADD COLUMN metadata_json TEXT");db.execSQL("ALTER TABLE knowledge_items ADD COLUMN updated_at INTEGER NOT NULL DEFAULT 0");db.execSQL("UPDATE knowledge_items SET updated_at=created_at");db.execSQL("UPDATE knowledge_items SET status='queued' WHERE status IN ('saved','needs_analysis')");
            db.execSQL("CREATE INDEX IF NOT EXISTS idx_ki_status ON knowledge_items(status)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ki_fingerprint ON knowledge_items(fingerprint)");
            db.execSQL("CREATE TABLE IF NOT EXISTS analyses(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,engine TEXT,version TEXT,output_json TEXT,created_at INTEGER NOT NULL)");db.execSQL("CREATE TABLE IF NOT EXISTS entities(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,kind TEXT,value TEXT,confidence REAL,created_at INTEGER NOT NULL)");db.execSQL("CREATE TABLE IF NOT EXISTS actions(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,action_text TEXT,due_text TEXT,status TEXT DEFAULT 'open',created_at INTEGER NOT NULL)");db.execSQL("CREATE TABLE IF NOT EXISTS relations(id INTEGER PRIMARY KEY AUTOINCREMENT,from_item_id INTEGER NOT NULL,to_item_id INTEGER NOT NULL,relation TEXT,confidence REAL,created_at INTEGER NOT NULL)");db.execSQL("CREATE TABLE IF NOT EXISTS examples(id INTEGER PRIMARY KEY AUTOINCREMENT,prompt_item_id INTEGER NOT NULL,input_item_id INTEGER,output_item_id INTEGER NOT NULL,rating INTEGER DEFAULT 0,notes TEXT,created_at INTEGER NOT NULL)");
            db.setTransactionSuccessful();}finally{db.endTransaction();}}
        if(oldV<3)createSemanticTables(db);
        if(oldV<4){createVisionTables(db);db.execSQL("UPDATE knowledge_items SET status='queued',analysis_error='' WHERE type IN ('SCREENSHOT','IMAGE') AND status='analyzed'");}
        if(oldV<5)CognitiveSchema.ensure(db);
        if(oldV<6)CognitiveSchema.ensure(db);
        if(oldV<7)CognitiveSchema.ensure(db);
    }

    public long insert(String type,String source,String title,String raw,String category,String tags,String attachment,String fingerprint,String metadata){if(fingerprint!=null&&!fingerprint.isEmpty()){long existing=findFingerprint(fingerprint);if(existing>0)return -existing;}long now=System.currentTimeMillis();ContentValues v=new ContentValues();v.put("type",type);v.put("source",source);v.put("title",title);v.put("raw_text",raw);v.put("extracted_text","");v.put("summary","");v.put("category",category);v.put("tags",tags);v.put("attachment_path",attachment);v.put("status","queued");v.put("fingerprint",fingerprint);v.put("analysis_error","");v.put("metadata_json",metadata);v.put("created_at",now);v.put("updated_at",now);return getWritableDatabase().insert("knowledge_items",null,v);}
    private long findFingerprint(String fp){Cursor c=getReadableDatabase().query("knowledge_items",new String[]{"id"},"fingerprint=?",new String[]{fp},null,null,null,"1");long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}

    public void addExample(long prompt,long input,long output,int rating,String notes){long now=System.currentTimeMillis();ContentValues v=new ContentValues();v.put("prompt_item_id",prompt);if(input>0)v.put("input_item_id",input);v.put("output_item_id",output);v.put("rating",rating);v.put("notes",notes);v.put("created_at",now);getWritableDatabase().insert("examples",null,v);addRelation(prompt,output,"example_result",1.0);if(input>0)addRelation(prompt,input,"example_input",1.0);}
    public void addRelation(long from,long to,String relation,double confidence){ContentValues v=new ContentValues();v.put("from_item_id",from);v.put("to_item_id",to);v.put("relation",relation);v.put("confidence",confidence);v.put("created_at",System.currentTimeMillis());getWritableDatabase().insert("relations",null,v);}

    public KnowledgeItem nextPending(){Cursor c=getReadableDatabase().query("knowledge_items",null,"status='queued'",null,null,null,"created_at ASC","1");KnowledgeItem k=c.moveToFirst()?from(c):null;c.close();return k;}
    public void markAnalyzing(long id){status(id,"analyzing","");}public void markFailed(long id,String error){status(id,"analysis_failed",error==null?"Unknown analysis error":error);}public void markFailedRetryable(long id,String error){status(id,"failed_retryable",error==null?"Retryable analysis error":error);}public void retry(long id){status(id,"queued","");}
    private void status(long id,String st,String err){ContentValues v=new ContentValues();v.put("status",st);v.put("analysis_error",err);v.put("updated_at",System.currentTimeMillis());getWritableDatabase().update("knowledge_items",v,"id=?",new String[]{String.valueOf(id)});}

    public void applyAnalysis(long itemId,AnalysisResult r){SQLiteDatabase db=getWritableDatabase();long now=System.currentTimeMillis();db.beginTransaction();try{ContentValues v=new ContentValues();v.put("title",r.title);v.put("summary",r.summary);v.put("category",r.category);v.put("tags",r.tags);v.put("extracted_text",r.extractedText);v.put("status","analyzed");v.put("analysis_error","");v.put("updated_at",now);db.update("knowledge_items",v,"id=?",new String[]{String.valueOf(itemId)});ContentValues a=new ContentValues();a.put("item_id",itemId);a.put("engine",r.engine);a.put("version",r.version);a.put("output_json",r.toJson());a.put("created_at",now);db.insert("analyses",null,a);db.delete("entities","item_id=?",new String[]{String.valueOf(itemId)});for(AnalysisResult.Entity e:r.entities){ContentValues x=new ContentValues();x.put("item_id",itemId);x.put("kind",e.kind);x.put("value",e.value);x.put("confidence",e.confidence);x.put("created_at",now);db.insert("entities",null,x);}db.delete("actions","item_id=?",new String[]{String.valueOf(itemId)});for(AnalysisResult.Action ac:r.actions){ContentValues x=new ContentValues();x.put("item_id",itemId);x.put("action_text",ac.text);x.put("due_text",ac.dueText);x.put("status","open");x.put("created_at",now);db.insert("actions",null,x);}db.delete("vision_fields","item_id=?",new String[]{String.valueOf(itemId)});for(AnalysisResult.VisionField f:r.visionFields){if(f.value==null||f.value.trim().isEmpty())continue;ContentValues x=new ContentValues();x.put("item_id",itemId);x.put("field_key",f.key);x.put("field_value",f.value);x.put("confidence",f.confidence);x.put("created_at",now);db.insert("vision_fields",null,x);}db.setTransactionSuccessful();}finally{db.endTransaction();}try{SemanticIndex.indexItem(this,itemId);}catch(Exception ignored){}}

    public KnowledgeItem getById(long id){Cursor c=getReadableDatabase().query("knowledge_items",null,"id=?",new String[]{String.valueOf(id)},null,null,null,"1");KnowledgeItem k=c.moveToFirst()?from(c):null;c.close();return k;}
    public ArrayList<String> actions(long itemId){ArrayList<String> out=new ArrayList<>();Cursor c=getReadableDatabase().query("actions",new String[]{"action_text","due_text"},"item_id=?",new String[]{String.valueOf(itemId)},null,null,"id ASC");while(c.moveToNext()){String s=c.getString(0),d=c.getString(1);out.add(s+(d==null||d.isEmpty()?"":"  •  "+d));}c.close();return out;}
    public ArrayList<String> entities(long itemId){ArrayList<String> out=new ArrayList<>();Cursor c=getReadableDatabase().query("entities",new String[]{"kind","value"},"item_id=?",new String[]{String.valueOf(itemId)},null,null,"id ASC");while(c.moveToNext())out.add(c.getString(0)+": "+c.getString(1));c.close();return out;}
    public ArrayList<String> visionFields(long itemId){ArrayList<String> out=new ArrayList<>();Cursor c=getReadableDatabase().query("vision_fields",new String[]{"field_key","field_value","confidence"},"item_id=?",new String[]{String.valueOf(itemId)},null,null,"id ASC");while(c.moveToNext()){String k=c.getString(0),v=c.getString(1);double conf=c.getDouble(2);out.add(k+": "+v+(conf>0?"  •  "+Math.round(conf*100)+"%":""));}c.close();return out;}
    public ArrayList<String> exampleDetails(long promptId){ArrayList<String> out=new ArrayList<>();String sql="SELECT e.rating,i.raw_text,o.raw_text FROM examples e LEFT JOIN knowledge_items i ON i.id=e.input_item_id JOIN knowledge_items o ON o.id=e.output_item_id WHERE e.prompt_item_id=? ORDER BY e.id DESC";Cursor c=getReadableDatabase().rawQuery(sql,new String[]{String.valueOf(promptId)});while(c.moveToNext()){int rating=c.getInt(0);String input=c.isNull(1)?"":c.getString(1),output=c.isNull(2)?"":c.getString(2);StringBuilder x=new StringBuilder();if(rating>0)x.append("Rating: ").append(rating).append("/5\n");if(input!=null&&!input.isEmpty())x.append("Input:\n").append(input).append("\n\n");x.append("Result:\n").append(output==null?"":output);out.add(x.toString());}c.close();return out;}
    public int pendingCount(){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM knowledge_items WHERE status IN ('queued','analyzing')",null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}public int failedCount(){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM knowledge_items WHERE status IN ('analysis_failed','failed_retryable')",null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}

    public ArrayList<KnowledgeItem> search(String q){if(q==null||q.trim().isEmpty())return lexicalSearch("",400);ArrayList<SemanticHit> hits=SemanticIndex.search(this,q,120);ArrayList<KnowledgeItem> out=new ArrayList<>();for(SemanticHit h:hits)out.add(h.item);return out;}
    public ArrayList<KnowledgeItem> lexicalSearch(String q,int limit){ArrayList<KnowledgeItem> out=new ArrayList<>();String sel=null;String[] args=null;if(q!=null&&!q.trim().isEmpty()){String w="%"+q.trim()+"%";sel="title LIKE ? OR raw_text LIKE ? OR extracted_text LIKE ? OR summary LIKE ? OR category LIKE ? OR tags LIKE ? OR id IN (SELECT item_id FROM entities WHERE value LIKE ?) OR id IN (SELECT item_id FROM actions WHERE action_text LIKE ?) OR id IN (SELECT item_id FROM vision_fields WHERE field_key LIKE ? OR field_value LIKE ?)";args=new String[]{w,w,w,w,w,w,w,w,w,w};}Cursor c=getReadableDatabase().query("knowledge_items",null,sel,args,null,null,"created_at DESC",String.valueOf(limit));while(c.moveToNext())out.add(from(c));c.close();return out;}

    private KnowledgeItem from(Cursor c){return new KnowledgeItem(g(c,"id"),s(c,"type"),s(c,"source"),s(c,"title"),s(c,"raw_text"),s(c,"extracted_text"),s(c,"summary"),s(c,"category"),s(c,"tags"),s(c,"attachment_path"),s(c,"status"),s(c,"fingerprint"),s(c,"analysis_error"),s(c,"metadata_json"),g(c,"created_at"),g(c,"updated_at"));}
    private String s(Cursor c,String n){int i=c.getColumnIndex(n);return i<0?"":c.getString(i)==null?"":c.getString(i);}private long g(Cursor c,String n){int i=c.getColumnIndex(n);return i<0?0:c.getLong(i);}
}
